### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by Peque** [micromouseonline/micromouse-maze#2]
I am able to compile the project, but not sure about how to use it nor for what it could be used for. :sweat_smile: 

Simply trying to execute `./libmaze_run` will fail. If I pass a `.maz` file as first parameter I get a segmentation fault (core dumped).

Looking at the CMake file it seems `libmaze_runX` is actually no different, is it? Is there an actual graphical interface implemented?

Adding a brief description to the README file would be great. :innocent: 

Anyway, thanks a lot for sharing this! :smile:

**Comment by micromouseonline** [comment]
Added some lines to readme.md
